---
new_page_extension: md
auto_deploy: false
admin_path: https://github.com/Nicolas-Turck/FAP-HUGO
webhook_url: 
sections:
- type: document
  path: FAP/themes/fapTh√®me/layouts
  label: start
  match: "**/*"
- type: directory
  path: ''
  label: FAP
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - fap-hugo
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: "/themes/faptheme/layouts/public"
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv/themes/faptheme/layouts/"
  working_dir: "/srv/themes/faptheme/layouts/"
  instant_preview_command: 'hugo server -D '
version: 0.76.5
